Sources/Console/Console/Console.swift
Added `foregroundExecute(...)` and `backgroundExecute(...)` as protocol requirements with default implementation in an extension.
This allows for overriding mentioned functions in concrete classes, so that Swift chooses the right function dynamically.
For more reference see [this article](https://medium.com/ios-os-x-development/swift-protocol-extension-method-dispatch-6a6bf270ba94#.8i7nreaww).
Also bumped the tag to 0.6.1, since this is a non-breaking release with purely additive changes.
=> Adjust ConsoleProtocol requirements to allow overriding

Sources/Console/Console/Console.swift
This is useful for when the response is raw data. If you want to get the `Data` response with the current `backgroundExecute` implementation, one would have to cast back into a `Data` object from a string, which is pointless.
=> Add `backgroundExecuteData` for getting raw `Data` response

Sources/Console/Console/Console.swift
This adds the ability to use an array of `String`s and variable arguments of `String` to call `foregroundExecute` and `backgroundExecute`.
`backgroundExecute` in the `ConsoleProtocol` now returns `Bytes` instead of `String`.
In addition, a generic version of `backgroundExecute` was implemented to allow calls like `console.backgroundExecute("ls") as String`.
=> Improved `backgroundExecute` and `foregroundExecute`

Sources/Console/Terminal/Terminal.swift
The current version only read a subset of environment variable.
This leads to this issue: https://github.com/vapor/toolbox/issues/109
Using all the defined environment variables solves the issue.
A similar PR has been done on the `swift-package-manager': https://github.com/apple/swift-package-manager/pull/400
=> Use all defined environment variables.

Sources/Console/Console/Console+Run.swift
When you add a group of commands to an executable, there are more IDs that need to be passed in to the executable arguments to run the command. Because there are more IDs in the arguments, that would break the `Command.value` method.
```swift
extension Command {
public func value(_ name: String, from arguments: [String]) throws -> String {
for (i, value) in signature.values.enumerated() {
if value.name == name {
// The index contained in `i` is incorrect
return arguments[i]
}
}
throw ConsoleError.argumentNotFound
}
}
```
To fix this issue, when a group of commands is found passed in to the `Console.run` method, we remove the first element in the `arguments` parameter, remove the extra ID:
```swift
if let command = runnable as? Command {
// got a command
foundCommand = command
} else if …
```
=> Fixed value fetching when a command is in a group

Sources/Console/Command/Command+Print.swift, Sources/Console/Command/Option.swift, Sources/Console/Console/Console+Options.swift, Sources/Console/Console/Console+Run.swift
This adds an optional property to the `Option` type, so it can be initialized with a short flag syntax, along with the full name:
```swift
Option(name: "foo", short: "f", help: [
"Nottin' here."
])
Option(name: "another", help: [
"HELP! HELP!"
])
```
When a short flag is added to the option, it is output in the help message:
```
Usage: ./.build/x86_64-apple-macosx10.10/debug/Executable fake [--foo -f] [--bizbaz -b] [--another]
Arugments:
Options:
foo f Nottin' here.
bizbaz b Here is some advice
Don't use this command
another HELP! HELP!
```
Short flags are also supported in the `Sequence.options` computed property, so they can be accessed the same way as long flags:
```
./.build/x86_64-apple-macosx10.10/debug/Executable fake -f -b=smile --another=one
// arguments.options = ["another": …
```
=> Added short flag syntax for command options

Sources/Console/Command/Command+Print.swift
Before, the assumption was made that a flag would always have the longest signature in the commands options. This causes extra space before the option names when a value name is the longest.
We now only add the length of the flag prefix the width count if we are calculating the width of a flag signature.
=> Fixed Width Calculation for Help Output

Sources/Command/Console+Run.swift, Sources/Command/Output+Autocomplete.swift
Adds an `--autocomplete` flag that returns all available arguments and options. This can be used to generate `bash_completion.d` scripts.
=> add autocomplete output

Sources/Command/CommandInput.swift
This prevents dangling `-` after detecting `-` prefixed flags which results in the following error: `CommandError.excessInput: Too many arguments or unsupported options were supplied`
=> Fix logic to parse single `-` prefixed flags

Sources/Command/CommandConfig.swift, Sources/Command/CommandInput.swift, Sources/Command/ConfiguredCommands.swift, Sources/Command/Output+Help.swift, Sources/Console/Console/Extensions/Console+Confirm.swift, Tests/CommandTests/CommandTests.swift, Tests/CommandTests/Utilities.swift, Tests/ConsoleTests/ConsoleTests.swift
=> Dep flag config

Sources/Command/Run/Console+Run.swift
It's getting pretty bogged down in the help command when it outputs for every error. Having just CommandError logs when uses command incorrectly, but not when command fails. That way the failure output can direct them more clearly
=> only output help for command errors

Package.swift, Sources/ConsoleKit/Command/Run/CommandInput.swift
Get rid of the `convergence` since we can use full-blown NIO2.
```
Test Suite 'All tests' passed at 2019-04-02 16:40:00.996.
Executed 19 tests, with 0 failures (0 unexpected) in 8.839 (8.840) seconds
```
=> NIO 2 is released

Sources/ConsoleKit/Command/Base/CommandRunnable.swift, Sources/ConsoleKit/Command/Base/Option.swift, Sources/ConsoleKit/Command/Command/Command.swift, Sources/ConsoleKit/Command/Group/BasicCommandGroup.swift, Sources/ConsoleKit/Command/Run/CommandContext.swift, Sources/ConsoleKit/Command/Run/Console+Run.swift, Sources/ConsoleKit/Command/Run/Output+Autocomplete.swift, Sources/ConsoleKit/Command/Run/Output+Help.swift, Tests/ConsoleKitTests/CommandTests.swift, Tests/ConsoleKitTests/Utilities.swift
This PR does a couple of small things to improve usability of ConsoleKit after the type safe updates:
1: In usage, it's a little weird that `help` is a member var but `signature` is static. They are related, so they should both have the same scope. I think instance makes the most sense since it's what Console 3.0 does and it gives the user more freedom.
2: In usage, using `Option(..., default: nil)` to get a value type option was not clear. I think the `OptionType` should be a required parameter since it was required in Console 3.0 (Option.value and Option.flag). I added a convenience `.value` where default = nil to make it easier to use.
3. There was a bug causing too many help outputs to be printed. I've added some code to ensure that only the last attempted runnable to run has its help …
=> typesafe improvements

Sources/ConsoleKit/Command/Argument.swift, Sources/ConsoleKit/Command/CommandError.swift, Sources/ConsoleKit/Command/CommandGroup.swift, Sources/ConsoleKit/Command/Option.swift, Tests/ConsoleKitTests/CommandErrorTests.swift, Tests/ConsoleKitTests/XCTestManifests.swift
As discussed, this changes CommandError from being a struct to an enum.
The naming of the cases is a bit iffy, and I'll happily change those to better names.
=> Implement enum based CommandError

.github/workflows/test.yml, Sources/ConsoleKit/Command/Argument.swift, Sources/ConsoleKit/Command/CommandInput.swift, Sources/ConsoleKit/Command/CommandSignature.swift, Sources/ConsoleKit/Command/Flag.swift, Sources/ConsoleKit/Command/Option.swift, Tests/ConsoleKitTests/CommandTests.swift
Adds a `.isPresent` property to the `Option` type that lets you check to see if the option was actually passed in when the command was called or not:
```
app command --option
// signature.option = nil
// signature.option.isPresent == true
app command
// signature.option = nil
// signature.option.isPresent == false
```
Look at that! We also don't have to pass in a value for an option any more. Because now we basically have a turnery value, (`nil`, `uninitialized`, `T()`), we need different ways of defining these states. So now you app can act differently based on whether the option is passed in or not.
There is also an `.initialized` property on all the signature value types. For now it doesn't really do you a whole lot, but it's something could be useful in the future so I decided to lay …
=> Allow Checking to See if a Option is Present in the Command Call

.github/workflows/test.yml, Sources/ConsoleKit/Command/CommandGroup.swift, Sources/ConsoleKit/Output/ConsoleText.swift
Previously, to generate `ConsoleText` you had to append strings using `+` and `consoleText()`.
```swift
let name = "Vapor"
console.output("Hello " + name.consoleText())
```
Now, `ConsoleText` supports string interpolation. 
```swift
console.output("Hello \(name)")
```
String interpolation also allows you to pass an optional `style` parameter for adding colors.
```swift
console.output("Hello \(name, style: .info)")
```
=> Make ConsoleText ExpressibleByStringInterpolation

Sources/ConsoleKit/Command/AnyCommand.swift, Sources/ConsoleKit/Command/Argument.swift, Sources/ConsoleKit/Command/CommandSignature.swift, Sources/ConsoleKit/Command/Commands.swift, Sources/ConsoleKit/Command/Completion.swift, Sources/ConsoleKit/Command/Option.swift, Sources/ConsoleKit/Utilities/GenerateAutocompleteCommand.swift, Sources/ConsoleKitExample/main.swift
Implements shell completion script generation for `bash` and `zsh`, and adds a flag to `Commands` to use it right out of the box:
```swift
// main.swift
// ...
var commands = Commands(enableAutocomplete: true)
// ...
let group = commands.group(help: "My command-line application")
try console.run(group, using: input)
// ...
```
The `CommandGroup` created will have an `autocomplete` command (a `GenerateAutocompleteCommand`) that can be used to generate shell completion scripts for the entire command hierarchy and its command-line arguments:
```
Usage: <executable> autocomplete [--shell,-s] [--output,-o] [--quiet,-q]
Generate shell completion scripts for the executable
Options:
shell Generate a completion script for SHELL [ bash | zsh ].
Defaults to the "SHELL" environment variable if …
```
=> Shell Completion Code Generation

Sources/ConsoleKit/Utilities/ConsoleLogger.swift
Updates `ConsoleLogger` to remove unnecessary quotes from the logger metadata.
Before:
```
[ INFO ] GET /error ["request-id": "4B6C1861-FE36-494F-AFE3-0FF7DAAC9738"] (Vapor/Responder/DefaultResponder.swift:35)
[ ERROR ] TestError 500: This is a test. ["request-id": "4B6C1861-FE36-494F-AFE3-0FF7DAAC9738"] (Development/routes.swift:167)
```
After:
```
[ INFO ] GET /error [request-id: 4B6C1861-FE36-494F-AFE3-0FF7DAAC9738] (Vapor/Responder/DefaultResponder.swift:35)
[ ERROR ] TestError 500: This is a test. [request-id: 4B6C1861-FE36-494F-AFE3-0FF7DAAC9738] (Development/routes.swift:167)
```
=> Remove extraneous quotes from logger metadata

.gitignore, Sources/ConsoleKit/Command/Command.swift, Tests/ConsoleKitTests/CommandTests.swift
Updates ConsoleKit to throw an error if unrecognized input is passed (#144). 
ConsoleKit currently ignores any input it is unable to parse. This makes simple typos confusing to debug, for example:
```sh
$ vapor run serve --port=1337
Running on localhost:8080
```
In the above example, invalid option syntax is being used. However, ConsoleKit simply ignores it.
After this update, invalid syntax will result in an error:
```sh
$ vapor run serve --port=1337
Error: Input not recognized: --port=1337
```
=> Error on unrecognized input

Sources/ConsoleKit/Command/CommandError.swift, Tests/ConsoleKitTests/CommandErrorTests.swift
Because `CommandError.description` includes the "Error: " label in the returned text, practically all formatted error output (especially such as found in vapor/toolbox) ends up printing `Error: Error: ...` for command errors. Since this table is redundant in the `description` of an `Error` anyway, we just remove it. The `description` of an `Error` is human-readable and therefore not parseable, and is thus not considered API, so this is considered a `semver-patch` change.
=> Fix double-output of "Error: " label for command errors

Sources/ConsoleKit/Utilities/ConsoleLogger.swift, Tests/ConsoleKitTests/LoggingTests.swift
Log metadata at all log levels. Previously, metadata was only logged at the `debug` log level.  (#149)
=> Log metadata at all log levels.

.github/workflows/test.yml, Sources/ConsoleKit/Terminal/Terminal.swift, Sources/ConsoleKit/Terminal/readpassphrase_linux.swift, Sources/ConsoleKitExample/DemoCommand.swift
`getpass()` is very, very old, and deprecated everywhere it exists. This PR switches to `readpassphrase()` on macOS, provides a (incomplete but sufficient) re-implementation of `readpassphrase()` based on that of `libbsd` for Linux, and adds an implementation for Windows using the `conio` interface.
=> Modernization of secure input using Console

.github/workflows/test.yml, Sources/ConsoleKit/Terminal/Terminal.swift, Sources/ConsoleKit/Terminal/readpassphrase_linux.swift, Sources/ConsoleKitExample/DemoCommand.swift
This is a rehash of #153 with improved compatibility and a better testing matrix.
`getpass()` is very, very old, and deprecated everywhere it exists. This PR switches to `readpassphrase()` on macOS, provides a (incomplete but sufficient) re-implementation of `readpassphrase()` based on that of `libbsd` for Linux, and adds an implementation for Windows using the `conio` interface.
=> Modernization of secure input using Console - take two

Sources/ConsoleKit/Terminal/Terminal.swift
Moved the declaration of the `pass` variable in `Terminal.input(isSecure:)` function so that it will compile for all OS targets.
=> Fixed compilation error when not building for MacOS, Linux or Windows

Sources/ConsoleKit/Command/CommandSignature.swift, Sources/ConsoleKit/Console.swift
Fixes the following warnings now produced by the Swift 5.4 compiler:
```
warning: using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead
public protocol Console: class {
^~~~~
AnyObject
```
=> Fix warnings from Swift 5.4 compiler

Package.swift, Sources/ConsoleKit/Command/Async/AnyAsyncCommand.swift, Sources/ConsoleKit/Command/Async/AsyncCommand.swift, Sources/ConsoleKit/Command/Async/AsyncCommandGroup.swift, Sources/ConsoleKit/Command/Async/AsyncCommands.swift, Sources/ConsoleKit/Command/Completion.swift, Sources/ConsoleKit/Command/Console+Run.swift, Sources/ConsoleKit/Utilities/GenerateAsyncAutocompleteCommand.swift, Sources/ConsoleKitAsyncExample/DemoCommand.swift, Sources/ConsoleKitAsyncExample/entry.swift, Tests/AsyncConsoleKitTests/AsyncCommandErrorTests.swift, Tests/AsyncConsoleKitTests/AsyncCommandTests.swift, Tests/AsyncConsoleKitTests/AsyncUtilities.swift
This adds experimental support for iOS and fixes up the concurrency stuff by making sure concurrency is available.
Resolves #172
=> Add experimental support for iOS

Sources/ConsoleKit/Command/Async/AnyAsyncCommand.swift, Sources/ConsoleKit/Command/Async/AsyncCommand.swift, Sources/ConsoleKit/Command/Async/AsyncCommandGroup.swift, Sources/ConsoleKit/Command/Async/AsyncCommands.swift, Sources/ConsoleKit/Command/Completion.swift, Sources/ConsoleKit/Command/Console+Run.swift, Sources/ConsoleKit/Utilities/GenerateAsyncAutocompleteCommand.swift, Sources/ConsoleKitAsyncExample/DemoCommand.swift, Sources/ConsoleKitAsyncExample/entry.swift, Tests/AsyncConsoleKitTests/AsyncCommandErrorTests.swift, Tests/AsyncConsoleKitTests/AsyncCommandTests.swift, Tests/AsyncConsoleKitTests/AsyncUtilities.swift
Fixes an issue where compilation would fail on older versions of macOS when using Swift 5.5
=> Fix compilation on older OSes

Package.swift, Sources/ConsoleKit/Utilities/ConsoleLogger.swift, Sources/ConsoleKitAsyncExample/entry.swift, Tests/ConsoleKitTests/LoggingTests.swift
This PR:
* Adds `MetadataProvider` support to `ConsoleLogger`.
* Makes it so the the package requires `swift-log` `1.5.1`+.
* Fixes these warnings:
```
[ WARNING ] Attempted to set metadataProvider on ConsoleLogger that did not implement support for them. Please contact the log handler maintainer to implement metadata provider support.
```
=> Add MetadataProvider support

Sources/ConsoleKit/Command/AnyCommand.swift, Sources/ConsoleKit/Command/Argument.swift, Sources/ConsoleKit/Command/CommandSignature.swift, Sources/ConsoleKit/Command/Commands.swift, Sources/ConsoleKit/Command/Completion.swift, Sources/ConsoleKit/Command/Flag.swift, Sources/ConsoleKit/Command/Option.swift, Sources/ConsoleKitAsyncExample/entry.swift, Sources/ConsoleKitExample/main.swift, Tests/ConsoleKitPerformanceTests/ConsoleLoggerPerformanceTests.swift, Tests/ConsoleKitTests/CommandTests.swift, Tests/ConsoleKitTests/Utilities.swift
Makes `Command` and many of the associated types, like `@Flag` and `@Option` `Sendable`.
Removes all Sendable warnings from ConsoleKit
=> Make Commands Sendable

Sources/ConsoleKit/Activity/ActivityIndicator.swift
Fixes an issue where `DispatchQueue` and friends are not `Sendable` on Linux so we need to suppress the warning
Resolves #189
=> Fix a Sendable warning on Linux

Sources/ConsoleKit/Activity/ActivityBar.swift, Sources/ConsoleKit/Utilities/AnySendableHashable.swift
`AnySendableHashable` introduced a breaking change where trying to pass concrete types that conform to `Sendable` and `Hashable` but the compiler couldn't infer they could be passed around as `AnySendableHashable`. This fixes the accesses for any dictionary (including `userInfo`) to fix an API break in https://github.com/vapor/console-kit/releases/tag/4.8.0
=> Fix `AnySendableHashable` regression

Sources/ConsoleKit/Utilities/LoggerFragment.swift
One of the goals of the `LoggerFragment` system was to make it simple to handle more complex logging logic by wrapping a custom log handler around the existing `LoggerFragment` system.
Unfortunately I forgot to give `LogRecord` a public initializer which makes doing that impossible.
=> Add a public initializer to LogRecord

Package@swift-5.9.swift, Sources/ConsoleKitCommands/Async/AsyncCommandGroup.swift, Sources/ConsoleKitCommands/Base/AnyCommand.swift, Sources/ConsoleKitCommands/Base/CommandGroup.swift, Sources/ConsoleKitCommands/Deprecated/MergedAsyncCommandGroup.swift, Sources/ConsoleKitTerminal/Activity/ActivityIndicator.swift, Sources/ConsoleKitTerminal/Output/Console+Wait.swift, Sources/ConsoleKitTerminal/Terminal/ANSI.swift, Sources/ConsoleKitTerminal/Terminal/Terminal.swift, Sources/ConsoleKitTerminal/Utilities/LoggerFragment.swift
Changes:
- Deprecates unnecessary API
- Corrects the sync `Command` adapter methods
- Cleans up some concurrency warnings
=> Revise async commands support

Sources/ConsoleKitCommands/Base/AnyCommand.swift
In a previous release, a change was made (by me) to how old `Command`s are integrated with `AsyncCommand`s which was unnecessary, offers no tangible benefit, possibly has a (very small) speed penalty, and is one of a small number of potential sources of runtime stalls. This reverts said ill-advised change.
=> Revert unnecessary command behavior change

Sources/ConsoleKitTerminal/Terminal/Terminal.swift, Sources/ConsoleKitTerminal/Terminal/readpassphrase_linux.swift
In order to compile this package against Musl libc, we need to not conflate `#if os(Linux)` with the ability to `import Glibc`. The common pattern for this is to use the `#if canImport` directive.
This patch adds support for Musl by replacing the `Glibc` import conditional alongside a new conditional import of `Musl`.
It also updates the `linux_readpassphrase` implementation to use the appropriate `sigaction` handler field for Musl.
=> Support compiling against Musl

Package.swift, Package@swift-5.9.swift, README.md, Sources/ConsoleKit/Docs.docc/theme-settings.json, Sources/ConsoleKitCommands/Docs.docc/theme-settings.json, Sources/ConsoleKitTerminal/Docs.docc/theme-settings.json, Sources/ConsoleKitTerminal/Terminal/readpassphrase_linux.swift, Sources/ConsoleKitTerminal/Utilities/LoggerFragment.swift, Tests/ConsoleKitTests/LoggingTests.swift
We now explicitly suppress excess `"` characters recursively in logger metadata.
Also bumps the package to a minimum of Swift 5.8 and fixes some warnings.
=> Make logged metadata a little more readable

.github/workflows/test.yml
Add CI to test support for Musl-based Linuxes, via Arch Linux
=> Try adding CI for MUSL

Sources/ConsoleKitTerminal/Activity/ActivityBar.swift, Sources/ConsoleKitTerminal/Activity/ActivityIndicator.swift, Sources/ConsoleKitTerminal/Terminal/Console.swift, Sources/ConsoleKitTerminal/Terminal/Terminal.swift
Long running loading/progress indicators create a lot of noisy output when an executable is outputting to Xcode's console, being captured to a file, or a piped to another command. e.g. #141 
This PR skips writing the animated output of an `ActivityIndicator` if the console will not handle it well.
=> Don't animate ActivityIndicator when outputting to a file

Sources/ConsoleKit/Docs.docc/index.md
Fixes the DocC link in the umbrella module. This works around DocC injecting in the base path to any non-fully qualified links.
Resolves #203
=> Fix DocC Links

Sources/ConsoleKitTerminal/Terminal/Terminal.swift
There are three things that cause Terminal to not build on Windows:
1. `isprint()` returns an `Int32` which requires an explicit comparison. Easy fix: just compare against `0`.
2. `_getch()` returns an `Int32`, but `Unicode.Scalar()` takes a `UInt32`. So we must cast.
3. The entire implementation of `size` was Posix-specific.  Add a Windows implementation.
=> Fix Windows build break in Terminal.

Sources/ConsoleKitTerminal/Terminal/ANSI.swift, Sources/ConsoleKitTerminal/Terminal/Console.swift, Sources/ConsoleKitTerminal/Terminal/Terminal.swift, Sources/ConsoleKitTerminal/Terminal/readpassphrase_linux.swift
This PR adds the imports necessary to get Android compiling again.
=> Fix Android support
